### ISSUE TITLE
Deprecate support for Python 3.7 (With #137)

### ISSUE THREAD

**Issue by Quantalabs** [epispot/epispot#138]
> NumPy has officially dropped support for Python 3.7, though Python won't end-of-life it for more than 9 months. This of course brings up the question of whether we, as epispot, should follow suit, considering that NumPy is one of our core dependencies and also that most of our other dependencies are in one way or another dependent on NumPy. 

_Originally posted by @quantum9Innovation in https://github.com/epispot/epispot/issues/137#issuecomment-1004335043_

It has been decided that support for 3.7 should be deprecated. the following are the steps for what needs to be done:

- [ ] Merge #137
- [x] #139
- [ ] #140
- [ ] #141

**Comment by Quantalabs** [comment]
New branch created for this issue. `3.7-deprecation`

**Comment by Quantalabs** [comment]
3.7 has been removed as a build requirement. Waiting for merge of #137 to be able to work o n #140 and #141

**Comment by quantum9Innovation** [comment]
#137 is currently being held up by #143, so we'll finish that as soon as possible

**Comment by Quantalabs** [comment]
Newer numpy version available, waiting on new dependabot PR.
