### ISSUE TITLE
Adding an en/ folder?

### ISSUE THREAD

**Issue by quantum9Innovation** [epispot/epispot#34]
Right now both pdoc docs and translations are stored on the root folder in gh-pages. There are two problems with this:
1. Modules with the same names as language codes will cause improper translations
2. Sub-modules are not being deleted
    a) The command that is being run in `docs.yml` is `rm *` which only deletes root files
    b) Files inside sub-modules will not be deleted

Possible fix:
Create an en/ folder for English documentation solving (1) and then delete all documentation inside en/ including sub-modules 
every time `docs.yml` is run solving (2).

**Comment by Quantalabs** [comment]
How would you get nightly docs for Spanish?

**Comment by quantum9Innovation** [comment]
@mt-gitlocalize will be used to keep track of changes and periodic translations but they won't be nightly or instant--rather they'll be updated each release
