### ISSUE TITLE
Importing and Exporting epispot models

### ISSUE THREAD

**Issue by Quantalabs** [epispot/epispot#36]
Importing and exporting epispot models with `.yml` and/or `.json` files created from a CLI or function would be extremely easy. I've already started to work on this.

## Related PR's and Issues:
- #25

**Comment by Quantalabs** [comment]
## New Requirements
- Possibly [PyFiglet](https://github.com/pwaller/pyfiglet) 
- [Clint](https://pypi.org/project/clint/)
- Google's [Python Fire](https://github.com/google/python-fire/) might be used too.

**Comment by quantum9Innovation** [comment]
# This has nothing to do with a CLI!
