### ISSUE TITLE
Get testing with pytest

### ISSUE THREAD

**Issue by Quantalabs** [epispot/epispot#47]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Testing with pytest makes everything quicker, more efficient, and faster.

**Describe alternatives you've considered**
Running each command manually, which is less efficient, and reports aren't given, unlike pytest, which files error and warning reports in the summary.

**Comment by quantum9Innovation** [comment]
Already working on this in #testing (PR not yet drafted)
