### ISSUE TITLE
Incorrect codecov reporting on PRs

### ISSUE THREAD

**Issue by quantum9Innovation** [epispot/epispot#57]
**Describe the bug**
@codecov officially does not recognize a *base report* from the `master` branch even though reports are being uploaded to codecov every commit via Travis CI, and can be seen [here](https://codecov.io/gh/epispot/epispot). Instead, codecov compares each PR to older commits with higher overall code coverage and fails because of this incorrect comparison.

**To Reproduce**
See #49, #50

**Expected behavior**
Codecov should instead find the latest reports from the `master` branch and compare *those* to the PR reports. Codecov should also provide detailed merge information on their website, which currently it does not do due to incorrect base reporting.

**Comment by Quantalabs** [comment]
As you can see with PR #58, codecov has proper reporting. #49 and #50 might have been deleted, or a temporary bug with codecov, however, it is fixed now.

**Comment by Quantalabs** [comment]
CORRECTION: With both PRs #50 and #49 the branches were deleted, and so codecov has no data on those. There was no bug with codecov.

**Comment by Quantalabs** [comment]
@quantum9Innovation any further issues?

**Comment by quantum9Innovation** [comment]
It seems that this issue has been resolved. We'll reopen it if anything new pops up.
