### ISSUE TITLE
Decreased legend visibility on `massive-plots`

### ISSUE THREAD

**Issue by quantum9Innovation** [epispot/epispot#66]
**Describe the bug**
The newly-added support for native stacked area charts in `massive-plots` (`epi.plots.native.stacked()`) lacks good legend visibility. This is due to the fact that for some reason, `matplotlib` fails to enforce the default white background for graphical elements on plots, resulting in no contrast between the graph itself and the legend.

**To Reproduce**
See `tests/plotting::test_full_native_stack`

**Expected behavior**
All legends should have a white background, thus standing out from the rest of the plot.

**Screenshots**
![epispot-issue-screenshot-3](https://user-images.githubusercontent.com/46249765/122330021-41b3c600-cee7-11eb-97cb-fb76a313d0be.png)
As shown in the plot above, legend colors blend in with the actual graphics.

**Python**
- Python Version: 3.9.4
- Operating System: Linux Mint 20 (Cinnamon)
- Epispot Version: `massive-plots` @ 4068117979dfe44374137f690255bfa5309f8e44
- Nightly (yes/no): yes: `pre-alpha`

**Anaconda**
- Anaconda Version: 4.10.1
- Matplotlib Version: 3.3.4

**Additional context**
This issue was mentioned in commit `4068117979dfe44374137f690255bfa5309f8e44`

**Comment by quantum9Innovation** [comment]
## Update

This will not be fixed in the upcoming PR merging `massive-plots` → `master`. We expect to close this issue with a separate patch PR that will be submitted before the `mini-plots` project is started.

**Comment by lisphilar** [comment]
Dear @quantum9Innovation,
To place the legend outside of the plotting area may be an altternative if it will not lead any problems.
```Python
ax.legend(loc="lower center", bbox_to_anchor=(0.5, -0.2), borderaxespad=0, ncol=2)
plt.tight_layout()
```

**Comment by quantum9Innovation** [comment]
@lisphilar Thank you for the advice! I've added this fix to a new branch (`patch-66`) via commit `0ca85d13b579e624ca5dfff701a7a7c4c62a0d6c`

The plot now looks like this:
![patch_66](https://user-images.githubusercontent.com/46249765/122654140-1a831180-d0fe-11eb-9e56-ec8d99bf4a62.png)

**Comment by quantum9Innovation** [comment]
I'll close the issue as soon as this branch is merged.

**Comment by lisphilar** [comment]
Thank you for updating and mentioning me at the commit!
