### ISSUE TITLE
Add Dependabot

### ISSUE THREAD

**Issue by quantum9Innovation** [epispot/epispot#79]
**Is your feature request related to a problem? Please describe.**
This feature is unrelated to any current issues in epispot. However, using Dependabot will not only make epispot's code more secure, but it allow epispot to support the latest versions of each of our dependencies. Previously, this was not a problem—however, as new versions of epispot add more and more external dependencies, it is critical that we monitor security vulnerabilities and release notes constantly.

**Describe the solution you'd like**
Solving this problem will require the following steps:
- [x] #80
- [x] #81
- [x] #87
- [x] #82

**Describe alternatives you've considered**
No alternative solutions have been considered. Dependabot is usually the norm for dependency management, especially since it integrates nicely with GitHub.

**Comment by quantum9Innovation** [comment]
This issue will be worked on in collaboration with @Quantalabs: /claim

**Comment by Quantalabs** [comment]
Will start work on #81

**Comment by quantum9Innovation** [comment]
No; wait for #80 to be finished. You'll be requested for review on the PR.

**Comment by quantum9Innovation** [comment]
Help wanted on #81 (see details on the issue)

**Comment by Quantalabs** [comment]
Added #87 to the task list, PR already submitted! Waiting to :shipit: at @quantum9Innovation review!

**Comment by quantum9Innovation** [comment]
This issue will be closed in around 6 hours
