### ISSUE TITLE
Install Dependabot and configure related settings

### ISSUE THREAD

**Issue by quantum9Innovation** [epispot/epispot#81]
*This issue is part of a series of tasks listed in #81.*

**Comment by Quantalabs** [comment]
@quantum9Innovation will start on #80, and I'll start work on this issue

/claim

**Comment by Quantalabs** [comment]
Work has started on branch `patch-81`

**Comment by quantum9Innovation** [comment]
Use:
```shell
git branch -m patch-#81 patch-81
git fetch origin
git branch -u origin/patch-81 patch-81
```
to rename your local branch. Always use `patch-{issue #}` instead of `patch-#{issue #}` when creating branch names.

**Comment by quantum9Innovation** [comment]
The problem right now is that we need some way to configure Travis CI to run tests with the latest dependencies that we support. That way, when `dependabot` updates our dependencies, we can run checks to confirm that our package is compatible with those updates.

`$ pip install -r requirements-dev.txt` has already failed on Travis CI. This is because `pip` installs all the dependencies simultaneously. And since `plotly`, one of the dependencies, does not correctly list `pandas` as a sub-dependency, we must add `pandas` to the `requirements-dev.txt` file. However, when `pip` simultaneously installs all the dependencies, `pandas` is not installed before `plotly` and this raises an error.

At least that's what we know so far. @Quantalabs any ideas?

**Comment by quantum9Innovation** [comment]
Currently the strategy is:
- Create new folder for requirements
- Store all the base requirements in requirements.txt *but* also include `pandas` despite not being a base requirement
- Store all additional requirements (not included in requirements.txt) in requirements-nightly.txt
- Store all developer requirements in requirements-dev.txt (don't include nightly and base requirements)
- Create build scripts to install and setup environment with the following structure
  - Create new virtual environment
  - Install base requirements
  - Install nightly requirements
  - Install dev requirements
  - Build epispot from the source
- Tell Travis CI to run build scripts on `pre-install` routine

Now, Travis CI will *first* install `pandas` and *then* install `plotly`, hopefully eliminating our problem.
